.PHONY: lint test generate

lint:
	go fmt ./...
	golint ./...
	go vet ./...
	errcheck ./...
	gocyclo -over 12 .

test:
	go test -v ./...

generate:
	protoc -I . --go_out=paths=source_relative:./goblinpb --go-grpc_out=paths=source_relative:./goblinpb goblin.proto