// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package goblinpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoblinServiceClient is the client API for GoblinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoblinServiceClient interface {
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (GoblinService_WatchClient, error)
}

type goblinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoblinServiceClient(cc grpc.ClientConnInterface) GoblinServiceClient {
	return &goblinServiceClient{cc}
}

func (c *goblinServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (GoblinService_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &GoblinService_ServiceDesc.Streams[0], "/goblin.GoblinService/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &goblinServiceWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GoblinService_WatchClient interface {
	Recv() (*NodeList, error)
	grpc.ClientStream
}

type goblinServiceWatchClient struct {
	grpc.ClientStream
}

func (x *goblinServiceWatchClient) Recv() (*NodeList, error) {
	m := new(NodeList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GoblinServiceServer is the server API for GoblinService service.
// All implementations must embed UnimplementedGoblinServiceServer
// for forward compatibility
type GoblinServiceServer interface {
	Watch(*WatchRequest, GoblinService_WatchServer) error
	mustEmbedUnimplementedGoblinServiceServer()
}

// UnimplementedGoblinServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGoblinServiceServer struct {
}

func (UnimplementedGoblinServiceServer) Watch(*WatchRequest, GoblinService_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedGoblinServiceServer) mustEmbedUnimplementedGoblinServiceServer() {}

// UnsafeGoblinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoblinServiceServer will
// result in compilation errors.
type UnsafeGoblinServiceServer interface {
	mustEmbedUnimplementedGoblinServiceServer()
}

func RegisterGoblinServiceServer(s grpc.ServiceRegistrar, srv GoblinServiceServer) {
	s.RegisterService(&GoblinService_ServiceDesc, srv)
}

func _GoblinService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoblinServiceServer).Watch(m, &goblinServiceWatchServer{stream})
}

type GoblinService_WatchServer interface {
	Send(*NodeList) error
	grpc.ServerStream
}

type goblinServiceWatchServer struct {
	grpc.ServerStream
}

func (x *goblinServiceWatchServer) Send(m *NodeList) error {
	return x.ServerStream.SendMsg(m)
}

// GoblinService_ServiceDesc is the grpc.ServiceDesc for GoblinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoblinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goblin.GoblinService",
	HandlerType: (*GoblinServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _GoblinService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "goblin.proto",
}
